on:
  push:
    branches:
      - master
name: Requirements
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Keep requirements.txt updated 
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.0
        args: export -f requirements.txt > requirements.txt
    - name: Keep requirements-dev.txt updated 
      uses: abatilo/actions-poetry@v1.1.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0.0
        args: export --dev -f requirements.txt > requirements-dev.txt
    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        COMMIT_MSG: |
          Updated requirements.txt files based on latest Poetry configuration
          skip-checks: true
      run: |
        # Hard-code user config
        git config user.email "gareth@morethanseven.net"
        git config user.name "Gareth Rushgrove"
        git config --get-regexp "user\.(name|email)"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout master
        git add .
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)
